### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by LaurentTreguier**
This PR simply adds French translations.

### CODE REVIEW

**Comment by martin31821** [comment]
We are currently in the process of implementing a new settings dialog which is more user friendly, as a result I would like to wait merging this until we finished doing so.

The background is that there will likely be some changed/new terms and I would like to include those in any upcoming translations.

Will definitely be merged, I think about in a week.

**Comment by martin31821** [comment]
Can you update the translations to reflect the changes we made to the settings dialog?
I think there are some new or changed terms.

**Comment by LaurentTreguier** [comment]
There were some new items indeed.

**Comment by martin31821** [comment]
Thanks for updating this. I will add you to the translators section of the About dialog.

**Pull request merged**
