### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by AlexGluck**

### CODE REVIEW

**Comment by martin31821** [comment]
Would you mind adding yourself as translator in the credits?
(see https://github.com/martin31821/cpupower/blob/master/data/cpupower-preferences.glade#L66)

Translation lgtm.

**Comment by AlexGluck** [comment]
Ok, ready. @martin31821

**Comment by AlexGluck** [comment]
How i can control updates translation? Now i help with 22 gnome extension with Russian translations, all they on github. New version extensions i managment over web site extensions.gnome.org. And after first configure don't control quality translation.

**Comment by martin31821** [comment]
Usually I create an issue and mention all translators to update the translation. 

Will merge this today.

**Pull request merged**
