### PR TITLE
Replace if/elses with cases, attempt sudo privs

### PR DESCRIPTION
**Pull request by tonylambiris**
This may be of interest, an attempt to clean up code readability replacing if/else with case statements. Also attempts to escalate sudo privileges right from the jump for writing new values to /sys fs.

Thoughts/comments appreciated.

### CODE REVIEW

**Comment by fin-ger** [comment]
Could you please preserve the 4 space indentation?

Otherwise it looks good.

And you can add yourself to the contributors list in the copyright notice ;)

@martin31821 Could you check this against your setups?

**Comment by martin31821** [comment]
@tonylambiris Can you explain what's the benefit of using sudo over policykit?
We can use sudo instead of policykit for sure, but we have to change the installation process and add a new rule in /etc/sudoers.

**Comment by tonylambiris** [comment]
@martin31821 I can't recall exactly at this point.I _want_ to say it had to do with GNOME/GDM/PolicyKit/etc and not being able to chance frequencies properly from the drop-down. I forgot I created this PR until my latest one, so if you want I can close we can close it out or cherry-pick parts if anything is of interested. :+1:

**Comment by fin-ger** [comment]
As sudo is not installed on all systems and policykit is more restrictive than sudo in granting superuser privileges, I will close this PR.

**Pull request closed without merging**
