### PR TITLE
WIP:Gnome-shell 40

### PR DESCRIPTION
**Pull request by chico-flojo**
included gnome-shell 40 in metadata

### CODE REVIEW

**Comment by fin-ger** [comment]
Hi, thanks for your PR!

I think this breaks the preferences dialog, but I can't test this as I don't have Gnome 40 available. See discussion in #150

**Comment by hmmanshh** [comment]
Umm, I will port it to GTK4 ASAP.
I'll update you when the project is done! rn I have my exams going on

**Comment by fin-ger** [comment]
:smile: we're currently all busy with uni stuff.

Don't put too much effort into the GTK 4 UI as it's not decided yet if it will make it to a normal release. We have to check first if GTK4 is supported in older Gnome releases and if not provide 2 preferences UIs: the old GTK3 and a new GTK4 UI. Also, the GTK4 UI will most likely be reworked once libadwaita hits 1.0 and is available to Gnome extensions.

Appreciate your work! We all lack time to do such a big update right now!

**Comment by fin-ger** [comment]
Gnome 40 support is now done and ready for merge in [feature/modular-cpufreqctl-backends](https://github.com/martin31821/cpupower/tree/feature/modular-cpufreqctl-backends). Closing this in favor of #151

**Pull request closed without merging**
