### PR TITLE
Add support for GNOME 42 (Ubuntu 22.04)

### PR DESCRIPTION
**Pull request by ankurkotwal**
Ensure that GNOME 42 is supported. This also adds support for Ubuntu 22.04, which includes GNOME 42 out of the box.

### CODE REVIEW

**Comment by ankurkotwal** [comment]
Fixes #188

**Comment by MrSquaare** [comment]
Confirms that it works for me, Ubuntu 22.04

**Comment by fin-ger** [comment]
Thanks for your testing!

For such a version increment to happen, I need testing in the most popular Linux distributions, including

 - [ ] all supported Ubuntu LTS releases
    - TODO: please collect which ones match
 - [ ] latest non-LTS release of Ubuntu
    - TODO: please check which release this is
 - [ ] latest debian testing, stable, and old-stable
    - TODO: please check which ones match
 - [ ] Fedora stable and old-stable
    - [ ] Fedora 34 (soon EOL, maybe skip?)
    - [ ] Fedora 35
    - [ ] Fedora 36 (currently testing, but stable soon, maybe also test?)
 - [ ] latest Arch

I currently don't have the time to do the testing, but if someone can confirm the following points for one of these distros, it would help a lot in getting a Gnome 42 (and 41) release done:

# Testing procedure

Run

```console
$ make install PREFIX=$HOME/.local
$ dbus-run-session -- gnome-shell --nested --wayland
```

and check for errors and warnings regarding `cpupower` in the console output while doing the following steps:


 1. Do clean installation (via the dropdown)
 2. Moving both sliders in the dropdown with
     1. Mouse
     2. Arrow keys
     3. Mouse wheel
 3. Toggle Turbo Boost
 4. Change Profile
 5. Toggle Auto-Switch (testing maybe not possible as VMs don't fire AC adapter events)
 6. Open Preferences and toggle all options
 7. Do 2-4 for all available backends
 8. Create a new profile and change its position (move up and down in the list)
 9. Set all values in that new profile
 10. Select it in the extensions dropdown menu
 11. Remove the profile
 12. Open About Window
 13. Uninstall tool and polkit rules (this is known to be flaky, if this fails this is not a stopper)
 14. Install latest version from Gnome Extensions
 15. Update with this version
 16. Check if update procedure is working (Note: this requires a version increment which is only done by `make release` which I have not done yet, so version in `installer.sh` and `cpufreqctl` needs to be incremented manually for testing)
 17. Native installs
     1. For debian-based distros
         1. do a clean install of the latest .deb for this extension
         2. build a deb for the new version and update with the package manager and check if the update is working
     2. For red-hat based distros
         1. do a clean install of the latest .rpm for this extension
         2. build a rpm for the new version and update with the package manager and check if the update is working

Global installation method and all other installation methods are not tested (at least by me). You can do it if you want and if you encounter any issues, I will do my best to fix them.

Orca (screen reader) support can only be tested in "real" gnome-shells (non-nested). At least I couldn't get Orca running in the nested gnome-shell, but it would be nice to have basic testing for screen-readers in all distros (profile management in preferences dialog is known to be hard-to-impossible to use with orca, this will be fixed when redesigning the preferences dialog and not a stopper for a new release).

**Comment by fin-ger** [comment]
Some other things to consider:

 - Which distros are using which Gnome version?
 - Can we remove Gnome 3.28 support?
    - Ubuntu was the last distro shipping this, I think
 - Add Gnome 41 as well
 - Is there any code specific to one of the Gnome versions removed?
   - Remove that code from the codebase

**Comment by hahaha2223** [comment]
On Pop_OS! 22.04 changing the metadata myself seems to work, but the preference window doesn't want to show.

**Comment by JustCryen** [comment]
So I downloaded the current AUR git version (like the previous one) and added 41 and 42 to the metadata.json
I haven't noticed any issues with 41 and it's mostly fine on 42 but I now noticed that both sliders get "stuck" to the mouse when I interact with them.
Essentially I'm able to move them and the frequency limit does change but now when I hover over the slider the limit gets moved to where I currently have my cursor located.
This happens on both of the sliders, it can also happen to both of them at the same time.

**Review by adityatelange — APPROVED** [review]
Works fine on Pop!_OS 22.04 LTS
image

**Comment by TJonCooper** [comment]
On Ubuntu 22.04 (Gnome Shell 42) - the preferences window pane does not open. I installed cpu-power-manager using the PPA, and then altered the metadata.json file to include "42" as this PR suggests. Everything else appears to work.

**Comment by fin-ger** [comment]
OK, looks like I have to do the testing myself. Those are contradicting results. PopOS should behave exactly the same as Ubuntu 22.04.

Also, forgive me when sounding harsh, I know you are just wanting to help. Can you **please** use the installation method above and stop editing the metadata on your own. I don't know whether you actually installed the correct version from the ppa where the metadata is the only change. The preferences window issue has appeared in previous versions. Also, if such an issue appears, please provide logs (as described in the Readme).

I'm sorry that such "simple" updates always take so long, but GNOME and distros have the tendency to always break our code with every new release. Therefore I switched to exhaustively testing each release on every single platform. If it turns out that PopOS behaves differently to Ubuntu 22.04, I'm afraid we have to include PopOS in our tests explicitely in the future, as it is a popular distro used by many users.

We have passed such version increments in the past and had users reporting complete failure of the extension with the issue tracker overwhelmed with reports. As long as the state for GNOME 41 and 42 of this extension is not clear, it is better to have a clear sign that these versions are not supported, yet. Most users understand that it just does not work for now.

As Ubuntu folks are now in the new position of running a bleeding edge GNOME version, you have to learn that it usually takes extensions half a year or so to adopt new GNOME releases. Ubuntu this time decided to go for GNOME 42 instead of an older release, so this is what all the Arch folks are experiencing since day one 😄

**Comment by TJonCooper** [comment]
Ouff - my apologies. I somehow managed to overlooked the installation method above. I can confirm on Ubuntu 22.04 (GNOME version = 42.0, Windowing System = X11) that, when installing via this method:

```
$ git clone https://github.com/ankurkotwal/cpupower.git -b fix/gnome42
$ cd cpupower
$ make install PREFIX=/home/<username>/.local
```
Everything is functioning as intended - including the preferences pane. Thank you for the great work and please do not feel rushed to release a version for Gnome 42.

**Comment by fin-ger** [comment]
> So I downloaded the current AUR git version (like the previous one) and added 41 and 42 to the metadata.json I haven't noticed any issues with 41 and it's mostly fine on 42 but I now noticed that both sliders get "stuck" to the mouse when I interact with them. Essentially I'm able to move them and the frequency limit does change but now when I hover over the slider the limit gets moved to where I currently have my cursor located. This happens on both of the sliders, it can also happen to both of them at the same time.

Hmm, I can't confirm that behavior. Although, I am currently an an AMD system. Does anyone else see this issue, too?

Nevertheless, I'll check Arch as working, as this is not blocking any core functionality. It's "just" annoying, I think.

**Comment by tnfru** [comment]
I'm on Pop!_OS 22.04 LTS x86_64 I ran the code snippet and the extensions seems to be installed and I can go to the settings via the extensions list, but it does not show up in the top bar. I triggered the option but that does not change anything. Gnome 42.

**Comment by fin-ger** [comment]
Hi @tnfru, thank you for your report!

Have you uninstalled any previous installation first?

Also, can you provide logs as described in the Readme?

```console
$ journalctl /usr/bin/gnome-shell
```

Make sure to remove sensitive information from the logs .

**Comment by tnfru** [comment]
Hey I figured the application was inactive, fixed it with:
`gnome-extensions enable cpupower@mko-sl.de`

**Comment by fin-ger** [comment]
@JustCryen Thank you for your detailed report!

@mastercaution Do you know what the error in `slider2.js` relates to? Do we need a special code in the slider for Gnome 42 onwards?

**Comment by fin-ger** [comment]
> Hey I figured the application was inactive, fixed it with: `gnome-extensions enable cpupower@mko-sl.de`
> 
> Works fine now

@tnfru Ah, thank you for the hint. I will include this in the instructions!

**Comment by mastercaution** [comment]
> @mastercaution Do you know what the error in slider2.js relates to? Do we need a special code in the slider for Gnome 42 onwards?

We can probably fix the sticky behavior by applying the following commit to our slider: https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/88a8ba086983ffa2669facb3a6e0c4e1e540a14f

Looks like this is the only change needed for Gnome 42 regarding the slider ... I hope so ^^

**Comment by JustCryen** [comment]
Yup, this did the trick!
Also, no more errors.

**Comment by fin-ger** [comment]
Then, we have to make sure this does not break older Gnome versions.

**Comment by fin-ger** [comment]
Alright, I prepared a patch which should introduce the new slider code only for Gnome 42. I am currently testing distros.

Ubuntu 18.04, Ubuntu 20.04, Fedora 35 and Fedora 36 are successful so far. I am continuing tests with Debian now and will include an additional test for latest PopOS.

**Pull request merged**
