### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by uno20001**
This commit introduces Hungarian translation for the software.

### CODE REVIEW

**Comment by fin-ger** [comment]
Thanks for adding this translation! Let's wait for #107 to finish first, it will add some more translation strings.

**Comment by fin-ger** [comment]
@uno20001 The new changes have landed on master. You can now update the translation, if you like.

**Comment by uno20001** [comment]
My git-fu is really lacking, so this is the best I could come up with at the moment. Is it completely useless or can something from it be salvaged?

**Comment by fin-ger** [comment]
I can do it, give me a sec :)

**Comment by fin-ger** [comment]
I fixed it. Just checkout and reset `translation_hu` now and commit as usual:

```
$ git fetch
$ git checkout translation_hu
$ git reset --hard origin/translation_hu
```

> Note: this assumes your remote (of the fork) is named `origin`

**Comment by fin-ger** [comment]
The master branch in your fork is a bit messed :D I can't fix it, because the master branch of your fork is not part of your PR, so I have no access to it. This is how to fix it:

```
$ git remote add upstream https://github.com/martin31821/cpupower.git
$ git fetch upstream
$ git checkout master
$ git reset --hard upstream/master
$ git push origin master:master --force
```

> Note: your master branch is most likely protected. You have to unprotect it in order to force push to it (you have some duplicated commits on it). [Configuring protected branches](https://help.github.com/en/github/administering-a-repository/configuring-protected-branches)

**Comment by uno20001** [comment]
> The master branch in your fork is a bit messed

That is indeed the case. It seems your instructions fixed it, thanks. Hopefully I didn't mess up anything with my commit. I didn't include the .mo file because it was in .gitignore, should I have done it?

**Comment by fin-ger** [comment]
No, they will be generated by the build process. We will take care of that. Your commit looks good. I think I can merge it now. Thank you for translating!

**Comment by uno20001** [comment]
Thanks for the patience and help!

**Pull request merged**
